name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run tests
        run: npm run test:ci

  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Preview markdown synchronization
        uses: Myastr0/mk-notes/preview@2.0.0
        with:
          input: './docs' # The path to the markdown file or directory to preview
          format: 'plainText' # The format of the preview ("plainText" or "json")


      - name: Update docs
        uses: Myastr0/mk-notes/sync@2.0.0
        with:
          input: './docs'
          destination: ${{ secrets.NOTION_DOC_PAGE_URL }}
          notion-api-key: ${{ secrets.NOTION_TOKEN }}
          clean: true
          lock: true